### ISSUE TITLE
Json struct

### ISSUE THREAD

**Issue by DEmacRE** [jarvisav/AnalystExtension#2]
Change the ID of the signature (not the case id) to be the name that we inserted as variable.

We have a new struct for the upper part of the signature:

> 	"action": "report",
> 	"id": "Name,
> 	"description": "Desc",
> 	"reference": "https://www.URL.com/",
> 	"actor": "TE",
> 	"category": "DrillDown",
> 	"cases": 

It will be neat if under category will be a drill down with this parameters:

> Fraudsters
> Adware
> Malicious
> Crypto Malware
> Ransomware
> Spyware 

Default action should be 'Report' and not 'Block'.

Condition 'No cases' is redundant.

@DavidBrowsi

**Comment by DavidBrowsi** [comment]
Done
